services:
  app:
    build: .
    container_name: finanzplaner
    ports:
      - "3000:80"
    volumes:
      - finanzplaner_storage:/rails/storage
    restart: unless-stopped
    environment:
      RAILS_ENV: development
      SECRET_KEY_BASE: dummy_secret_base

volumes:
  finanzplaner_storage: